apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: generic-pipeline
spec:
  params:
    - name: git-url
      description: The url for the git repository
    - name: git-revision
      description: The git revision (branch, tag, or sha) that should be built
      default: master
  tasks:
    - name: setup
      taskRef:
        name: setup
      params:
        - name: git-url
          value: $(params.git-url)
        - name: git-revision
          value: $(params.git-revision)
  
    - name: dockerfile-lint
      when:
        - input: $(tasks.setup.results.dockerfile)
          operator: in
          values: ["true"]
      taskRef:
        name: dockerfile-lint
      runAfter:
        - setup
      params:
        - name: git-url
          value: "$(tasks.setup.results.git-url)"
        - name: git-revision
          value: "$(tasks.setup.results.git-revision)"