apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: generic-pipeline
spec:
  params:
    - name: git-url
      description: The url for the git repository
    - name: git-revision
      description: The git revision (branch, tag, or sha) that should be built
      default: master
    - name: git-reponame
      description: Name of the git repository
    - name: project-name
      description: Name of the project
  tasks:
    - name: setup
      taskRef:
        name: setup
      params:
        - name: git-url
          value: $(params.git-url)
        - name: git-revision
          value: $(params.git-revision)
  
    - name: lint-dockerfile
      when:
        - input: $(tasks.setup.results.dockerfile)
          operator: in
          values: ["true"]
      taskRef:
        name: lint-dockerfile
      runAfter:
        - setup
      params:
        - name: git-url
          value: "$(tasks.setup.results.git-url)"
        - name: git-revision
          value: "$(tasks.setup.results.git-revision)"

    - name: build-tag-push
      when:
        - input: $(tasks.setup.results.dockerfile)
          operator: in
          values: ["true"]
      taskRef:
        name: build-tag-push
      runAfter:
        - lint-dockerfile
      params:
        - name: git-url
          value: "$(tasks.setup.results.git-url)"
        - name: git-revision
          value: "$(tasks.setup.results.git-revision)"
        - name: image-server
          value: "de.icr.io"
        - name: image-namespace
          value: "$(params.project-name)-cr"
        - name: image-repository
          value: "$(params.git-reponame)"
        - name: image-tag
          value: "$(tasks.setup.results.git-revision"