apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: tekton-eventlistener
spec:
  triggers:
    - name: trigger-github
      interceptors:
        - ref:
            name: "cel"
          params:
          - name: "filter"
            value: "header.User-Agent.contains('Github')"
      bindings:
        - name: github-binding
      template:
        name: trigger-generic-pipeline