apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: tekton-eventlistener
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: trigger-github
      interceptors:
        - ref:
            name: "cel"
          params:
          - name: "filter"
            value: "header['User-Agent'].contains('Github')"
      bindings:
        - ref: github-binding
      template:
        ref: trigger-generic-pipeline