apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: tekton-eventlistener
spec:
  triggers:
    - name: trigger-github
      interceptors:
        - ref:
            name: "github"
            kind: ClusterInterceptor
            apiVersion: triggers.tekton.dev
          params:
          - name: "eventTypes"
            value: ["pull_request", "push"]
      bindings:
        - ref: github-binding
      template:
        ref: trigger-generic-pipeline