apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github-binding
spec:
  params:
  - name: gitrevision
    value: $(body.head_commit.id)
  - name: gitrepositoryurl
    value: $(body.repository.url)
  - name: gitreponame
    value: $(body.repository.name)
  - name: gitevent
    value: $(header.X-GitHub-Event)
  - name: projectname
    value: $(extensions.projectname)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: gitlab-binding
spec:
  params:
  - name: gitrevision
    value: $(body.commits.id)
  - name: gitrepositoryurl
    value: $(body.project.web_url)