apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: trigger-generic-pipeline
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: $(tt.params.gitreponame)-
      spec:
        params: 
          - name: git-url
            value: $(tt.params.gitrepositoryurl)
          - name: git-revision
            value: master
          - name: revision
            value: $(tt.params.gitrevision)
        pipelineRef:
          name: generic-pipeline